# Deps
kotlin.version=2.4.0
kotlin.wrappers.version=2026.6.7
kfc.version=19.7.0
seskar.version=4.60.0
# MUI Deps
mui-material.version=7.3.11
mui-icons-material.version=7.3.11
mui-base.version=5.0.0-beta.70
mui-system.version=7.3.11
mui-lab.version=7.0.1-beta.25
mui-x-date-pickers.version=7.29.4
mui-x-tree-view.version=7.29.10
# Flags
org.gradle.jvmargs=-Xms2g -Xmx4g
org.gradle.parallel=true
kotlin.js.yarn=false
