import baseui.Field
import baseui.FieldControlChangeEventDetails
import baseui.FieldRootActions
import baseui.TransitionStatus
import baseui.className
import baseui.render
import baseui.style
import emotion.react.Global
import emotion.react.styles
import js.objects.unsafeJso
import react.CSSProperties
import react.FC
import react.Props
import react.create
import react.dom.html.ReactHTML.button
import react.dom.html.ReactHTML.p
import react.dom.html.ReactHTML.span
import react.useRef
import react.useState
import web.cssom.Border
import web.cssom.ClassName
import web.cssom.Color
import web.cssom.Display
import web.cssom.FlexDirection
import web.cssom.LineStyle.Companion.solid
import web.cssom.Position
import web.cssom.integer
import web.cssom.number
import web.cssom.px
import web.html.InputType
import web.html.email

// Live check of the generated `baseui` field declarations, and the only usage reference for them in
// the repository. Same contract as `BaseUiMenu` / `BaseUiSlider`: every member of the `Field`
// namespace object is mounted, so a key that stops existing at runtime takes the page down instead of
// failing at some user's call site.
//
// What only running this can establish, each of it something `field` was picked to exercise:
//  - `transitionStatus` is a real sealed type now, not `Any?`. Both forms of use are here:
//    `Field.Error`'s className helper interpolates it, since a seskar union still reads back as the
//    bare JavaScript string, and `Field.Validity` *compares* it against `TransitionStatus.ending`,
//    which is what closing the gap actually bought. The comparison has to be on a part that stays
//    mounted — `Field.Error` is being removed when its own status becomes `ending`.
//  - `FieldValidityProps.children` is a *formatting callback* over the part's own state and, unlike
//    `Slider.Value`'s, came out fully typed. Assigning a lambda has to reach that member and Base UI
//    has to call it.
//  - `FieldControlProps.onValueChange` came out typed too, `FieldControlChangeEventDetails` and all —
//    the first Base UI event-details type reached from a type position rather than from a marker.
//  - `FieldRootActions` is an imperative handle behind an `actionsRef` that is still `Any?`. The
//    button below is the only proof the members line up with what Base UI puts in the ref.
//  - The four state types that upstream declares as nothing but `extends FieldRootState`
//    (`FieldControlState`, `FieldDescriptionState`, `FieldItemState`, `FieldLabelState`) — every
//    `state.valid` / `.filled` / `.touched` / `.disabled` below is reaching through one of them.
//  - The label/description wiring is generated by Base UI, not by us: `Field.Label` has to come out
//    with a `for` pointing at the control's id, and the control with an `aria-describedby` pointing at
//    the description and the error.
//
// Class names are literal and `bui-field-` prefixed so they can be asserted against in the DOM.
//
// One expected Base UI warning about `render` for the whole page — not one per call site; see the
// note in `BaseUiSlider` and gap 15. This file adds a second `render` call site and the console still
// carries exactly one, naming whichever lambda reached Base UI first.

// The shape `FieldValidityData.state` widens to. Upstream is an inline object of eleven booleans plus
// `valid: boolean | null`, which has no Kotlin structural equivalent, so the generated member is
// `Any?` with the whole TypeScript in a marker. Reading it means naming that shape here.
private external interface ValiditySnapshot {
    val valueMissing: Boolean
    val typeMismatch: Boolean
    val customError: Boolean
    val valid: Boolean?
}

val BaseUiField = FC<Props> {
    var address by useState("")
    var lastChange by useState("-")
    var lastAction by useState("-")
    val actions = useRef<FieldRootActions>(null)

    Global {
        styles {
            // A sibling sample (`SliderStylization`) lays an absolutely positioned element over the
            // whole viewport, so anything interactive needs a stacking context of its own.
            ".bui-field-root" {
                position = Position.relative
                zIndex = integer(1)
                display = Display.flex
                flexDirection = FlexDirection.column
                gap = 4.px
                width = 320.px
                marginBottom = 24.px
                fontSize = 13.px
            }

            ".bui-field-label" { color = Color("#666666") }
            ".bui-field-label--filled" { color = Color("#111111") }

            ".bui-field-control" {
                padding = 6.px
                border = Border(1.px, solid, Color("#cccccc"))
                borderRadius = 4.px
            }
            ".bui-field-control--invalid" { borderColor = Color("#c00000") }
            ".bui-field-control--valid" { borderColor = Color("#0a7d00") }

            ".bui-field-description" { color = Color("#888888") }
            ".bui-field-error" { color = Color("#c00000") }
            ".bui-field-validity" { color = Color("#444444") }

            ".bui-field-item" {
                display = Display.flex
                flexDirection = FlexDirection.column
                gap = 2.px
                padding = 6.px
                border = Border(1.px, solid, Color("#eeeeee"))
                borderRadius = 4.px
            }
        }
    }

    p {
        className = ClassName("bui-field-status")
        +"email=$address change=$lastChange action=$lastAction"
    }

    Field.Root {
        // Value arm of `className`, alongside the state-typed helpers used further down.
        className = ClassName("bui-field-root")

        name = "email"

        // `Form.ValidationMode` is still widened (BASE_UI_TODO.md gap 6), so the raw string is what a
        // call site writes. `onChange` rather than the default `onSubmit` because there is no `<Form>`
        // here and the error has to be reachable by typing.
        validationMode = "onChange"
        validationDebounceTime = 0

        // `validate` is `Any?`: its parameters are `unknown` and `Form.Values`, neither of which
        // translates, so the whole callback is widened (gap 14) and the types are stated here.
        validate = { value: Any?, _: Any? ->
            val text = value as? String
            if (!text.isNullOrEmpty() && !text.endsWith("@example.com")) "Must be an @example.com address"
            else null
        }

        // `actionsRef` is `Any? /* React.RefObject<FieldRootActions | null> */` — the ref assigns, and
        // what comes back out of it is `FieldRootActions`.
        actionsRef = actions

        Field.Label {
            // `filled` comes from `FieldRootState`, which every one of these state types inherits and
            // declares nothing else of its own.
            className { state ->
                if (state.filled) ClassName("bui-field-label bui-field-label--filled")
                else ClassName("bui-field-label")
            }
            // Explicit rather than defaulted, so a rename upstream fails here.
            nativeLabel = true
            +"Email"
        }

        Field.Control {
            required = true
            type = InputType.email
            placeholder = "you@example.com"
            value = address

            className { state ->
                when (state.valid) {
                    false -> ClassName("bui-field-control bui-field-control--invalid")
                    true -> ClassName("bui-field-control bui-field-control--valid")
                    else -> ClassName("bui-field-control")
                }
            }

            // Typed end to end: `value` is a `String` and `eventDetails` is the generated
            // `FieldControlChangeEventDetails`, whose `reason` comes from the hand-written
            // `BaseUIChangeEventDetails` parent.
            onValueChange = { next: String, details: FieldControlChangeEventDetails ->
                address = next
                lastChange = "${next.length}ch/${details.reason}"
            }
        }

        Field.Description {
            className = ClassName("bui-field-description")

            // Callback arm of `render`. `+props` is what carries the generated `id` that the control's
            // `aria-describedby` points at — drop it and the description stops being announced while
            // still looking right. No children in the builder, since `+props` already has them.
            render { props, _ -> p.create { +props } }

            +"Only @example.com addresses are accepted."
        }

        // `match = true` always shows while the field is invalid, whatever the reason.
        Field.Error {
            // Interpolating `transitionStatus` yields the bare JavaScript string, the way every seskar
            // union does — the class is `bui-field-error--null` while nothing is transitioning. The
            // *comparison* against a member of the sealed type is in `Field.Validity` below, which
            // stays mounted long enough to observe it; this part is being removed when its own status
            // becomes `ending`.
            className { state -> ClassName("bui-field-error bui-field-error--${state.transitionStatus}") }
            match = true
        }

        // `match` also takes a `keyof ValidityState`, which is the other arm of the same `Any?`.
        Field.Error {
            className = ClassName("bui-field-error bui-field-error--required")
            match = "valueMissing"
            +"An email address is required."
        }

        // Renders no element at all — a callback over the field's validity and nothing else. This is
        // also the only place `FieldValidityData`'s members are read.
        Field.Validity {
            children = { state ->
                val snapshot = state.validity.unsafeCast<ValiditySnapshot>()
                span.create {
                    className = ClassName("bui-field-validity")
                    // `leaving` is the point of closing gap 5: a comparison against a member of the
                    // sealed type, which the `Any?` this used to be could not express. It reads true
                    // while the error is transitioning out, i.e. as the field becomes valid.
                    val leaving = state.transitionStatus == TransitionStatus.ending
                    +"valid=${snapshot.valid} missing=${snapshot.valueMissing} typeMismatch=${snapshot.typeMismatch} custom=${snapshot.customError} errors=${state.errors.size} status=${state.transitionStatus} leaving=$leaving"
                }
            }
        }

        button {
            className = ClassName("bui-field-validate")
            // Reported rather than fire-and-forget: `actionsRef` is `Any?`, so nothing checks that
            // what Base UI puts in the ref is a `FieldRootActions` — only calling it does.
            onClick = {
                val handle = actions.current
                lastAction = if (handle == null) "actionsRef never filled" else {
                    handle.validate()
                    "validate() called"
                }
            }
            +"Validate imperatively"
        }
    }

    // `Field.Item` is the grouping shape `checkbox-group` and `radio-group` will reuse: its own label
    // and description around one control, inside a field that owns the name.
    Field.Root {
        className = ClassName("bui-field-root")
        name = "nickname"

        Field.Label {
            className = ClassName("bui-field-label")
            +"Nickname"
        }

        Field.Item {
            className { state ->
                // `touched` is `FieldRootState` again, reached through `FieldItemState`, which upstream
                // declares with an empty body.
                ClassName("bui-field-item bui-field-item--${if (state.touched) "touched" else "pristine"}")
            }

            // Callback arm of `style`, over the part's own state.
            style { state ->
                unsafeJso<CSSProperties> {
                    opacity = if (state.disabled) number(0.5) else number(1.0)
                }
            }

            Field.Label {
                className = ClassName("bui-field-label")
                +"Display name"
            }

            Field.Control {
                className = ClassName("bui-field-control")
                placeholder = "optional"
            }

            Field.Description {
                className = ClassName("bui-field-description")
                +"Shown next to your comments."
            }
        }
    }
}
